name := "speedstream"
version := "1.0"
scalaVersion := "2.12.10"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.4"
libraryDependencies += "org.mongodb.scala" %% "mongo-scala-driver" % "2.8.0"
